open System
open System.Reflection
open Argu
open FSharpLint.Framework.Ast
open FSharpCoverageCorrector.Core
open FSharpCoverageCorrector.Core.Corrections
open FSharpCoverageCorrector.IO.Cobertura
open FSharpLint.Framework.ParseFile
  
type CliArguments =
  | [<ExactlyOnce>] Coverage_File of coverage_file: string
  | [<ExactlyOnce>] Project_File of project_file: string
  | [<ExactlyOnce>] Output_File of output_file: string
  
  with
    interface IArgParserTemplate with
        member s.Usage =
            match s with
            | Coverage_File _ -> "The input coverage file, in Cobertura XML format."
            | Project_File _ -> "The project (.fsproj) file."
            | Output_File _ -> "The output file, in XML format."

let programName = Assembly.GetExecutingAssembly().GetName().Name
  
let errorHandler = ProcessExiter(colorizer = function ErrorCode.HelpText -> None | _ -> Some ConsoleColor.Red)
let parser = ArgumentParser.Create<CliArguments>(programName=programName, errorHandler = errorHandler)

let printErrorAndExit message =
  eprintfn $"Error: %s{parser.PrintUsage(message)}"
  exit 1
      
let parseResult = parser.Parse(inputs = Environment.GetCommandLineArgs()[1..])

let toolsPath = Ionide.ProjInfo.Init.init()
let projectFilesInfo = match loadProjectFiles (parseResult.GetResult Project_File) toolsPath with
                        | Ok fileParseInfoList -> fileParseInfoList
                        | Error err ->
                          let errMsg = match err with
                                        | ProjectLoadError.ProjectInfoError e -> $"An error occurred loading project information: {e}"
                                        | ProjectLoadError.ParseFileError failureList ->
                                          failureList |> List.fold (fun str failure ->
                                                            str + Environment.NewLine +
                                                            match failure with
                                                            | ParseFileFailure.AbortedTypeCheck -> "Aborted type check"
                                                            | ParseFileFailure.FailedToParseFile parseFailures ->
                                                              parseFailures
                                                              |> Array.map (fun f -> $"Failed to parse file ${f.FileName}: ${f.Message}")
                                                              |> String.concat Environment.NewLine
                                                            )
                                                            "Error parsing source files: "
                          printErrorAndExit errMsg

let anrps = loadAstNodeRuleParamsFromProject projectFilesInfo

match readPackagesFromCoberturaFile projectFilesInfo anrps (parseResult.GetResult Coverage_File) with
| Error ex ->
  let errMsg = $"Error reading data from input file: {ex.Message}{Environment.NewLine}{ex.ToString()}{Environment.NewLine}"
  printErrorAndExit errMsg
| Ok packages ->
  // apply the corrections
  let correctedPackages = packages
                          |> List.map correctAutogeneratedClasses
                          |> List.map correctBranchCoverage
  let xml = generateXml correctedPackages
  try
    xml.Save(parseResult.GetResult Output_File)
  with
  | ex -> let errMsg = $"Error writing data to {Output_File}: {ex.Message}{Environment.NewLine}{ex.ToString()}{Environment.NewLine}"
          printErrorAndExit errMsg

// finally, if successful, return ok exit code
Environment.ExitCode <- 0