/// <summary>
///  Provides a function to combine the code coverage information of an F# package
/// from classes autogenerated at runtime with classes defined at runtime. 
/// </summary>
[<AutoOpen>]
module FSharpCoverageCorrector.Core.Corrections.AutogeneratedClasses

open FSharpCoverageCorrector.Core
open FSharpCoverageCorrector.Core.Utils
open System.Text.RegularExpressions

/// A group of methods autogenerated from the same source.
type private MethodAutoGeneratedGroup =
  {
    /// The source file, if available.
    SourceFile: SourceFile option
    /// The name of the original class.
    ClassName: string
    /// The name of the original method.
    MethodOfClass: Method
    /// the autogenerated classes.
    AutoGeneratedClasses: Class list
  }
  
  /// The line number extents of the group.
  member this.LineNumberExtents =
    let allLineNumbers = (this.AutoGeneratedClasses |> List.collect (fun c -> c.Lines)) @ this.MethodOfClass.Lines
                         |> List.map (fun l -> l.Number)
    List.min allLineNumbers, List.max allLineNumbers

/// Given a package, finds and groups all autogenerated classes.
let private groupAutoGeneratedClasses (pkg: Package) =
  // attempts to find the class in origClasses with the given className.
  // If unsuccessful, will then try to find a nested class with the same name as className, (className/className),
  // as can occur in the case where the class is in a module with the same name.
  let tryFindOrigClass (className:string) (methodName: string) (origClasses: Class list) =
    // see if we found a class with the same name as className that also has a method with the same name as methodName
    let origClassOpt = origClasses |> List.tryFind (fun c -> c.Name = className &&
                                                             List.contains methodName (c.Methods |> List.map (fun m -> m.Name)))
    match origClassOpt with
    | Some oc -> Some oc
    | None -> // if not found, try to find a class with the name className/className, that has a method by the name methodName
              let nestedName = className + "/" + Array.last (className.Split("."))
              origClasses |> List.tryFind (fun c -> c.Name = nestedName &&
                                                             (List.exists (fun (m: Method) -> m.Name = methodName) c.Methods))
              
  let autoGenClassRegexp = Regex(@"^.*/.*@[[1-9][0-9]*(-[1-9][0-9]*){0,1}$") // the pattern used to search for autogenerated classes
  // partition the autogenerated classes from the original classes
  let autoGenClasses, origClasses = pkg.Classes
                                    |> List.partition (fun c -> autoGenClassRegexp.IsMatch c.Name)
  // create 'groups' of autogenerated classes, of the form (className, methodName, classes)
  let autoGenGroups = autoGenClasses
                      |> List.groupBy (fun c ->
                                         let split = c.Name.Split [|'/'; '@'|]
                                         split[0], split[1])
                      |> List.map (fun (classAndMethodNames, classes) -> (fst classAndMethodNames), (snd classAndMethodNames), classes)
  // partition the autogenerated groups into those for which a corresponding original method has been found, and those for which no method was found
  let found, notFound  = autoGenGroups
                         |> List.map (fun (className, methodName, agClasses) -> 
                                        className, methodName, agClasses, (tryFindOrigClass className methodName origClasses))
                         |> List.partition (fun (_, _, _, origClassOpt) -> origClassOpt.IsSome)
  // create the MethodAutoGeneratedGroups for those which are found
  let foundGroups = found
                    |> List.map (fun (_, methodName, agClasses, origClassOpt) ->
                        let origClass = origClassOpt.Value
                        let origMethodOpt = (origClass.Methods |> List.tryFind (fun m -> m.Name = methodName))
                        let origMethod = origMethodOpt.Value
                        { SourceFile = origClass.SourceFile
                          ClassName = origClass.Name
                          MethodOfClass = origMethod
                          AutoGeneratedClasses = agClasses })
                    
  // for each autogenerated group tht hasn't been found, try to find the original method by looking up line extents
  let results = (seq {
    for nf in notFound do
      let _, _, autoGenClasses, _ = nf
      let firstClassWithLinesOpt =
        autoGenClasses
        |> List.tryFind (fun cls -> cls.Lines.Length > 0)
      match firstClassWithLinesOpt with
      | Some firstClassWithLines ->
          if firstClassWithLines.Lines.Length > 0 then
            let firstLine = firstClassWithLines.Lines[0] // we know that autoGenClasses is not empty, and Lines is also not empty, so this is safe
            let lineFoundOpt = foundGroups
                               |> List.tryFind (fun grp -> let minLine, maxLine = grp.LineNumberExtents
                                                           firstLine.Number >= minLine && firstLine.Number <= maxLine)
            match lineFoundOpt with
            | Some grp ->
              yield Ok {grp with AutoGeneratedClasses = autoGenClasses @ grp.AutoGeneratedClasses}
            | None -> 
              let autogeneratedClassNames = autoGenClasses |> List.map (fun c -> c.Name) |> String.concat "; "
              // todo: use a special error type
              yield Error $"No matching original method found for autogenerated classes: {autogeneratedClassNames}"
      | None -> ()
  } |> Seq.toList)
  
  let updatedAutoGenGroups = results |> unwrapOks
  let failedToCorrect = results |> unwrapErrors
  
  // concat the update groups and the found groups, throwing away any found groups that were updated
  let updatedAndFoundGroups = (updatedAutoGenGroups @ foundGroups) |> List.distinctBy (fun c -> c.ClassName, c.MethodOfClass)
  updatedAndFoundGroups, failedToCorrect
  
/// Given a group and a package, corrects the package, combining the autogenerated classes with
/// the original method and removing the autogenerated classes in the group.
let private correctMethod (grp: MethodAutoGeneratedGroup) (package: Package) =
  // merge two lines.
  let mergeLines (l1: Line) (l2: Line) =
    if l1.Number <> l2.Number then
      failwith "expected numbers to be equal"
    if l1.Contents <> l2.Contents then
      failwith "expected contents to be equal"
    let hits = l1.Hits + l2.Hits
    let conditions = l1.Conditions
                     |> List.map (fun c1 -> 
                                   let c2Opt = l2.Conditions |> List.tryFind (fun cond -> cond.Number = c1.Number)
                                   match c2Opt with
                                   | Some c2 -> if c1.Coverage > c2.Coverage then c1 else c2
                                   | None -> c1)
    { Number = l1.Number
      Hits = hits
      Conditions = conditions
      Contents = l1.Contents }
  
  // merge two sets of lines.
  let mergeLines (lines1: Line list) (lines2: Line list) =
    let notOnlyLine2 = List.fold
                         (fun updated l1 ->
                                    let l2Opt = lines2 |> List.tryFind (fun l -> l.Number = l1.Number)
                                    match l2Opt with
                                    | Some l2 -> (mergeLines l1 l2)::updated
                                    | None -> l1::updated )
                         []
                         lines1
    let onlyLine2 = lines2 |> List.filter (fun l2 ->  notOnlyLine2
                                                      |> List.tryFind (fun l -> l.Number = l2.Number)
                                                      |> Option.isNone)
    notOnlyLine2 @ onlyLine2 |> List.sortBy (fun l -> l.Number)
  
  // update the lines by merging
  let updatedLines = List.fold (fun lines (ac: Class) -> mergeLines lines ac.Lines)
                                grp.MethodOfClass.Lines
                                grp.AutoGeneratedClasses
  let updatedMethod = { grp.MethodOfClass with Lines = updatedLines }
  let origClass = package.Classes |> List.find (fun c -> c.Name = grp.ClassName)
  // replace the methods in the original class
  let updatedClass =
    let methods = replace (fun (m1: Method) (m2: Method) -> m1.Name = m2.Name) updatedMethod origClass.Methods
    match origClass.SourceFile with
    | Some sf -> Class.Create(origClass.Name, sf, methods, origClass.NonMethodLines)
    | None -> Class.Create(origClass.Name, origClass.Filename, methods, origClass.NonMethodLines)
  let inAutoGenClasses (c: Class) = (List.tryFind (fun (agc: Class) -> c.Name = agc.Name) grp.AutoGeneratedClasses).IsSome // function to determine if a class is in the list of autogenerated classes
  // update the list of classes to replace the original class with the updated class, and exclude auto-generated classes
  let updatedClasses = package.Classes
                      |> replace (fun c1 c2 -> c1.Name = c2.Name) updatedClass // replace the original class with the updated class
                      |> List.filter (fun c -> not (inAutoGenClasses c))
  // update the package with the updated classes
  let updatedPkg = { package with Classes=updatedClasses }
  updatedPkg

/// <summary>
/// Given a package, correct any autogenerated classes created at runtime within it.
/// 'Correct' in this context means merge the coverage for each autogenerated class into the method of origin, and remove the autogenerated class.
/// </summary>
/// <param name="package">The package to correct.</param>
/// <result>The corrected package and a list of errors of classes that could not be corrected.</result>
let correctAutogeneratedClasses (package: Package) =
  let autogeneratedGroups, errors = groupAutoGeneratedClasses package
  let correctedPackage =
    List.fold (fun pkg group -> correctMethod group pkg)
      package
      autogeneratedGroups
  correctedPackage, errors  